### ISSUE TITLE
Diagram view.  Request to group navigation controls.

### ISSUE THREAD

**Issue by spainala** [awslabs/aws-media-services-application-mapper#100]
This request is to group the diagram view navigation controls.   Currently, large diagrams require the operator to move back and forth across the page to zoom in and traverse left.  Let's group the navigation controls so that the operator does not have to mouse back and forth across the page.
![MSAM_diagram_navigation](https://user-images.githubusercontent.com/60242286/75184652-94b5a880-56f9-11ea-8881-29fc20852154.png)

**Comment by ClarkAtAmazon** [comment]
Here is the proposed changed to the UI to resolve this issue. 

![image](https://user-images.githubusercontent.com/61600894/75589150-ec704e80-5a2e-11ea-8a50-bb15ed40bc01.png)

The the initial location is set by the VIS.JS CSS. 
To overwrite the default location without needing to host our own modified version of the VIS.JS CSS we can place our changes in the HEAD > STYLE element of the index.html file. 

The changes above are derived from the following CSS 

```
.vis-zoomIn {
  right: auto;
  left: 150px;
}

.vis-zoomOut {
  right: auto;
  left: 190px;
}

.vis-zoomExtends {
  bottom: 10px !important;
  right: auto;
  left: 230px;
}
```

**Comment by JimTharioAmazon** [comment]
Let's give people a couple days to comment on this UI change, and barring any conflicts, we should be able to add this one to 1.5.5.
