### ISSUE TITLE
Adding selected node(s) to existing tile doesn't take effect

### ISSUE THREAD

**Issue by morjoan** [awslabs/aws-media-services-application-mapper#101]
Selecting specific nodes and adding them to an existing tile doesn't seem to be taking effect (via Tiles -> Add Selected Node to Tile). There are no obvious errors in the console when hitting the Save button.
Creating a new tile out of a selected diagram tab works just fine, however.

**Comment by JimTharioAmazon** [comment]
I found a problem in channel_menu.js and fixed an event handler loop.
