### ISSUE TITLE
"Add New Diagram" link difficult to find for new users.

### ISSUE THREAD

**Issue by ClarkAtAmazon** [awslabs/aws-media-services-application-mapper#104]
When showing new users MSAM, it has been observed that many have a difficult time locating the Add New Diagram option from the Diagram Drop Down.

Currently the Add New Diagram option is difficult to find

![image](https://user-images.githubusercontent.com/61600894/75590010-2fcbbc80-5a31-11ea-8fe6-213556341fcd.png)

The proposed change would be to move the option to the top of the Drop Down as depicted below

![image](https://user-images.githubusercontent.com/61600894/75590123-6dc8e080-5a31-11ea-8e1f-71c0df43273a.png)

**Comment by JimTharioAmazon** [comment]
Let's give people a couple days to comment on this UI change, and barring any conflicts, we should be able to add this one to 1.5.5.
