### ISSUE TITLE
Searching can be confusing for new users

### ISSUE THREAD

**Issue by ClarkAtAmazon** [awslabs/aws-media-services-application-mapper#105]
The Search Input and Search Results are detached in the User Interface. 

We observed confusion when asking new users to search for something. 

The proposed changed would move and or duplicate the Search Input to be visible under the Search tab. 

Currently
![image](https://user-images.githubusercontent.com/61600894/75590897-352a0680-5a33-11ea-81e6-682d472f6f11.png)

Proposed Change
 
![image](https://user-images.githubusercontent.com/61600894/75591305-46bfde00-5a34-11ea-9398-f1ceddb7614c.png)

**Comment by JimTharioAmazon** [comment]
Sample code for mirroring fields: http://jsfiddle.net/brynner/KnXJc/

**Comment by JimTharioAmazon** [comment]
The search fields (top-right, bottom-left) sync on Enter or button click.

![image](https://user-images.githubusercontent.com/33331284/94071064-24165d80-fda8-11ea-96d9-f6657690c24a.png)
