### ISSUE TITLE
Pipeline alert overlay shows [A,B] for single pipelines

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#115]
Can the pipeline overlay for MediaLive adjust for single pipeline channels? It shows `Pipeline alerts: [X,Y]` for single pipeline channels.

**Comment by Joaquin6** [comment]
I can add this for single pipelines

**Comment by Joaquin6** [comment]
did this pass testing?

**Comment by JimTharioAmazon** [comment]
Done and closed.
