### ISSUE TITLE
Use something other than PipelinesRunningCount for connection mapping

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#119]
We discovered today that MediaLive and Multiplex's PipelinesRunningCount attribute goes to 0 when the resource is IDLE. This means connection records can disappear when a channel isn't running. We want to maintain the structure of the resources at all times, so something other than PipelinesRunningCount should be used here. I think the length(Destinations) might be useful.

**Comment by Joaquin6** [comment]
I can take a look at the length of Running Pipelines as a different source of truth.
