### ISSUE TITLE
Create a separate CloudFormation template for IAM policies/roles

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#122]
To help with installation in strict environments, we'd like to create a 5th template that only installs resources for IAM. This template would contain all of the policies and roles needed by resources created in other templates, such as Lambda. IAM resources in other templates will come out.

A template for IAM resources will allow an organization with IT duties separated across groups to install MSAM in multiple stages. A security team could first create the required IAM resources followed by an operations team to install the application and configure it.

The existing templates will be modified to accept IAM role ARNs as parameters.

Users without special installation requirements will be able to use the master template to install everything in a single region as before.

INSTALL.md will need an update after this change to include the new template.

**Comment by morjoan** [comment]
The new IAM CFN template creates the IAM roles required by the other MSAM templates (core, web, dynamo, and events).  
When installing via master template, these are automatically passed to the nested templates. If installing MSAM templates individually, these roles will need to be provided as a parameter.
This also creates the policy group required by #123.
