### ISSUE TITLE
Need a guide to cover configuration of SSM/hybrid/encoder resources

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#125]
This may be a new markdown file since the topic is so broad. We will need to guide people on updating the role for an EC2 or setting up the agent on a physical host. Pointers to existing documentation here are totally acceptable - no need to rewrite that.

There will need to be a little more detail around encoders and the metrics that are generated and sent to CloudWatch. Maybe we need a simple tutorial of creating an alarm for one of the encoder metrics and mapping that back to the encoder node?

**Comment by morjoan** [comment]
Added documentation on managed instances (MANAGED_INSTANCES.md).
