### ISSUE TITLE
Support MediaLive channel to S3 bucket connections

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#127]
We currently support S3 bucket to MediaLive inputs, but not on the outbound.

**Comment by morjoan** [comment]
<img width="357" alt="Screen Shot 2020-09-24 at 3 13 42 PM" src="https://user-images.githubusercontent.com/33331296/94205662-96567300-fe78-11ea-800f-82fc8d0198ff.png">
