### ISSUE TITLE
Bundle 3rd-party JS and CSS dependencies with the web deployment content

### ISSUE THREAD

**Issue by spainala** [awslabs/aws-media-services-application-mapper#135]
Operators have requested the ability to operate MSAM in a VPC with no public internet access.  

Currently, the MSAM index.xml requires public internet access for page load.  Can we include these dependencies in the MSAM installer?  

https://github.com/awslabs/aws-media-services-application-mapper/blob/master/html/index.html

**Comment by JimTharioAmazon** [comment]
We'll start by looking at a tool called webpack, which may help us bundle the 3rd-party JavaScript and CSS dependencies with the build files. This would cause the front-end to load everything from a single CloudFront distribution or web host.

**Comment by JimTharioAmazon** [comment]
1. Mirroring the CDN dependencies to the /external/ folder within the web content.

2. Extending the TTL for CloudFront to the maximum since the content won't change until an update, which also sends an invalidation command. We might as well keep content in edge cache as long as possible.

**Comment by JimTharioAmazon** [comment]
3. Update web CloudFormation template to set MIME type for .css files to text/css.

**Comment by JimTharioAmazon** [comment]
4. Require.js modules need to be mirrored locally too.
