### ISSUE TITLE
Support MediaStore container to CloudFront distribution connections

### ISSUE THREAD

**Issue by morjoan** [awslabs/aws-media-services-application-mapper#136]
We currently support S3 buckets and MediaPackage endpoints to CloudFront distributions, but not MediaStore to CloudFront.

**Comment by AdamTylerLynch** [comment]
+1

**Comment by morjoan** [comment]
<img width="548" alt="Screen Shot 2020-09-24 at 2 40 49 PM" src="https://user-images.githubusercontent.com/33331296/94203869-111d8f00-fe75-11ea-9710-5b6e23e6f0d2.png">
