### ISSUE TITLE
Tile view filter selection persistence

### ISSUE THREAD

**Issue by spainala** [awslabs/aws-media-services-application-mapper#151]
Please make the tile selection persistent.  1.7.0 tile filter selection "Show only Alarm/Alert Tiles" is cleared when refreshing the web interface.  The web interface reverts to "Showing All Tiles" following a page refresh.

<img width="598" alt="tile view filter selection" src="https://user-images.githubusercontent.com/60242286/92829080-a22a3b80-f388-11ea-9d40-bf7428c60483.png">

**Comment by morjoan** [comment]
Added a tile-view in the settings database to persist last selected tile view. Default during deployment is to show all tiles.
