### ISSUE TITLE
Provide control for clearing of all diagrams & tiles

### ISSUE THREAD

**Issue by 090media** [awslabs/aws-media-services-application-mapper#153]
If the user wants to delete all diagrams and tiles in an MSAM instance, it must be done one-by-one. With a large number of assets, that can be tedious. There should be some sort of DELETE ALL button (with confirmation dialog) that wipes out everything.

**Comment by JimTharioAmazon** [comment]
This might be a good fit under the Advanced Settings dialog.

**Comment by JimTharioAmazon** [comment]
Located in Settings/Advanced Settings under Bulk Delete.

![image](https://user-images.githubusercontent.com/33331284/96323296-5e52d380-0fd1-11eb-9347-cf59d021446f.png)

**Comment by 090media** [comment]
Awesome! Thanks, Jim!

**Comment by 090media** [comment]
Hi again. Sorry to bug you and I'm probably overlooking some simple thing, but I attempted to update to the latest build (so I could use this new Bulk Delete functionality) by updating the root stack in CloudFormation. I've done it twice now and nothing seems to change. Beyond that, it looks like some of the stacks are stuck in "UPDATE IN PROGRESS" mode. My last attempt was over two hours ago. Any idea what's going on? Thanks.

**Comment by 090media** [comment]
UPDATE: I tried to update the main stack again and chose to "Replace current template" and pointed it at the latest msam-all-resources-release.json. Now, I see that all stacks say "UPDATE COMPLETE" except there's a second entry for the root stack (USWE2MSAM) that says "UPDATE COMPLETE CLEANUP IN PROGRESS". Do I just need to wait for that to finish or something? 

If I access the MSAM install, the Browser Application is still the old build (1594682397) but the Endpoint API look to be newer now (1604080050). Any help you can offer would be amazing. Thanks!

**Comment by 090media** [comment]
![Screenshot 2020-12-02 162610](https://user-images.githubusercontent.com/48948131/100950523-58ea1380-34c1-11eb-9505-482bb8e2629c.jpg)

**Comment by 090media** [comment]
Finally finished and I have a new build now. Very confusing process. Apologies for the fire drill. Closing.

**Comment by JimTharioAmazon** [comment]
Hi Mark, sorry you had a hard time with the upgrade. Updating the "all-resources" stack will upgrade all the nested stacks in one operation. Can you tell us which region you were upgrading? Can you also share an image of the Events tab from the top stack? It will show the launch/completion times of each nested stack. I am curious to know where the slow down occurred.

**Comment by 090media** [comment]
Us-west-2 was the region.

Here’s a shot of the Events tab…
[cid:image001.png@01D6C979.F084F740]

Cheers.
Mark
