### ISSUE TITLE
MediaLive standard channel connection issues require page refresh

### ISSUE THREAD

**Issue by spainala** [awslabs/aws-media-services-application-mapper#154]
We are observing unexpected connection behavior when one of two MediaConnect sources are stopped.  Both MediaLive input pipeline connections, Medialive output pipelines and Multiplex output pipelines are red. 

Stop a MediaConnect flow.  Results in this unexpected diagram view with two red connections.

<img width="1188" alt="unexpected_behavior_following_emx_stop" src="https://user-images.githubusercontent.com/60242286/92838025-22ee3500-f393-11ea-8db8-42560b5fd887.png">

A page refresh displays the expected diagram view with a single red connection and no Multiplex connection issues.

<img width="1438" alt="expected_behavior_after_page_refreshes" src="https://user-images.githubusercontent.com/60242286/92838172-529d3d00-f393-11ea-828c-0850f1db53d8.png">

**Comment by JimTharioAmazon** [comment]
Fixed.
