### ISSUE TITLE
Request to add MSAM architecture diagram to install documentation

### ISSUE THREAD

**Issue by spainala** [awslabs/aws-media-services-application-mapper#157]
The MSAM AWS implementation guide offers  a great overview of the MSAM architecture.
https://aws.amazon.com/solutions/implementations/media-services-application-mapper/

Can we add a similar architecture diagram to the MSAM install docs?

**Comment by JimTharioAmazon** [comment]
Here is the 4+1 architectural views for MSAM. 
https://github.com/awslabs/aws-media-services-application-mapper/blob/master/docs/software-architecture.md

**Comment by JimTharioAmazon** [comment]
The Deployment View shows what templates/code go to which services.
The Physical View shows the installed configuration.

**Comment by JimTharioAmazon** [comment]
Let's add navigation from the root documentation files to the software architecture (bottom nav links), and rename that file to readme.md for easy viewing.

**Comment by morjoan** [comment]
Updated all doc files to link to Architecture doc. Also updated doc files to include missing nav links (some docs were missing links to REST API and/or Contributing page) and remove redundant links (eg. INSTALL.md doesn't need nav link to install).
