### ISSUE TITLE
Restructure MSAM project to align with the AWS Solutions layout

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#168]
This will impact where some files live in the GitHub folder structure and require some changes to the build scripts.

**Comment by JimTharioAmazon** [comment]
I pushed a new branch with the solution package skeleton expanded in there for us to start. I called the branch **solution-reorg**.

I added the skeleton under **solution-pkg/** and my thoughts were to remove/move things to here as we go. Eventually it should be the only thing in the branch, and once we’re done we should be able to move the root of **solution-pkg/** to the root of the repository. 

I am hoping this makes it easier to work incrementally on relocating files and scripts.

**Comment by morjoan** [comment]
Build and deploy scripts are now under deployment, code under source, and all documentation under docs.
