### ISSUE TITLE
Documentation update request: Preserve user defined nodes when duplicating tables between two stacks

### ISSUE THREAD

**Issue by spainala** [awslabs/aws-media-services-application-mapper#169]
Currently the "Example: Duplicating Tables Between Two Stacks" instructions in INSTALL.md mentions skipping the Content table.  Skipping content table removes user defined nodes. If the procedure is followed as currently written, user defined nodes are lost.

Please consider updating the INSTALL.md instructions with a procedure that preserves user defined nodes when duplicating tables.

https://github.com/awslabs/aws-media-services-application-mapper/blob/master/INSTALL.md

**Comment by morjoan** [comment]
Updated documentation. Currently fix is in solution-reorg branch.
