### ISSUE TITLE
Deploy fails with CloudWatch template error

### ISSUE THREAD

**Issue by robclemamzn** [awslabs/aws-media-services-application-mapper#177]
The MSAM deploy currently fails with this CloudWatch error:
'Parameter CloudWatchEventsTableName failed to satisfy constraint: Please enter a value for this field.'  
- The template has no value for this field.
-  I have no idea what the dynamoDB tables should look like

I was attempting to invoke it in my home region of us-west-2 if that matters.
Also: when you change the region,  the setup tool clears the template field, which you have to re-populate by restarting setup and copying the value before you change the region.  The default template path should be listed on the page text independent of the field value...

**Comment by robclemamzn** [comment]
I suggest testing the deploy from a clean user-level AWS account.

**Comment by JimTharioAmazon** [comment]
Which template causes this error for you?

```
https://rodeolabz-us-west-2.s3.amazonaws.com/msam/msam-all-resources-release.json
https://rodeolabz-us-west-2.s3.amazonaws.com/msam/msam-browser-app-release.json
https://rodeolabz-us-west-2.s3.amazonaws.com/msam/msam-core-release.json
https://rodeolabz-us-west-2.s3.amazonaws.com/msam/msam-dynamodb-release.json
https://rodeolabz-us-west-2.s3.amazonaws.com/msam/msam-events-release.json
https://rodeolabz-us-west-2.s3.amazonaws.com/msam/msam-iam-roles-release.json
```

**Comment by robclemamzn** [comment]
Hello sir –

The displayed error was:

'Parameter CloudWatchEventsTableName failed to satisfy constraint: Please enter a value for this field.'

The template has no value for this field.

**Comment by robclemamzn** [comment]
It was the default template  https://rodeolabz-us-west-2.s3.amazonaws.com/msam/msam-dynamodb-release.json

Pasted that URL into the form after setting region to ‘us-west-2’

**Comment by JimTharioAmazon** [comment]
Until we have an update on documentation, you can use the following guide to install the entire solution with a single template.

https://github.com/awslabs/aws-media-services-application-mapper/blob/master/INSTALL.md#master-template-all-resources

**Comment by JimTharioAmazon** [comment]
This will be addressed in the new Implementation Guide and Landing Page releasing with 1.8.0.
