### ISSUE TITLE
Please enable point-in-time recovery by default for MSAM DynamoDB tables

### ISSUE THREAD

**Issue by spainala** [awslabs/aws-media-services-application-mapper#187]
Please enable point-in-time recovery for DynamoDB tables used in the CloudFormation templates. This will provide a recovery mechanism in the event of needing to restore a DynamoDB table.

![point-in-time-recovery](https://user-images.githubusercontent.com/60242286/107831826-d93fb700-6d43-11eb-9857-faed279d98fe.png)

**Comment by spainala** [comment]
![Uploading point-in-time-recovery.png…]()

**Comment by JimTharioAmazon** [comment]
P-I-T recovery enabled for all tables.
_DynamoDB maintains continuous backups of your table for the last 35 days._
