### ISSUE TITLE
Incorrect URL provided for root template install instructions

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#193]
URL is missing '-release' at the end.

Should be:
https://rodeolabz-us-west-2.s3.amazonaws.com/aws-media-services-application-mapper/latest/aws-media-services-application-mapper-release.template

https://github.com/awslabs/aws-media-services-application-mapper/blob/master/docs/INSTALL.md#root-template-install-all-msam-resources

**Comment by morjoan** [comment]
Step 2 of the Deployment section of main README should be updated as well. Sample link given is missing _-release_ in the template name.

```
1. Get the link of the solution template uploaded to your Amazon S3 bucket.
s3://my-bucket-aws-region/solution-name/latest/aws-media-services-application-mapper-release.template

```

**Comment by JimTharioAmazon** [comment]
Fix pushed to trunk.
