### ISSUE TITLE
Create a document on how to use MSAM to monitor channels created by MediaLive's workflow wizard

### ISSUE THREAD

**Issue by morjoan** [awslabs/aws-media-services-application-mapper#217]
MediaLive recently released a Workflow Wizard that helps create a live streaming channel. Resources (MediaLive channel, MediaPackage channel and endpoints, CloudFront distribution) created by the wizard are tagged with keys and values used by MSAM to automatically create diagrams with these resources for monitoring. We need a doc that outlines how this works.

**Comment by JimTharioAmazon** [comment]
I made a couple of minor edits for clarity, but very well done and easy to follow. Thanks!

**Comment by morjoan** [comment]
Thanks for reviewing, Jim.
