### ISSUE TITLE
Frequent updates to informational layer make nodes flicker

### ISSUE THREAD

**Issue by morjoan** [awslabs/aws-media-services-application-mapper#33]
Probably need a different way to update the informational layer so as not to trigger it too often, giving that flicker effect. I only see this on the local hosted app.
Code hosted on bucket doesn't seem to update information layer at all (might be addressed if informational layer is reworked).

**Comment by JimTharioAmazon** [comment]
We can compare previous/current rendering of the SVG code of a given node and determine if it needs to be replaced and updated in the diagram surface.

**Comment by JimTharioAmazon** [comment]
Needed to remove automatically generated elements IDs by SVG.js to successfully compare SVG code between renders.
