### ISSUE TITLE
Audit IAM permissions needed by custom resources

### ISSUE THREAD

**Issue by tdfacer** [awslabs/aws-media-services-application-mapper#36]
First off, MSAM is very impressive and it looks like it could be a great fit for our live-stream monitoring needs.  

I have noticed that there are some fairly loose permissions on a couple of the stacks referenced in the install guide.  This seems to be particularly true for the custom CloudFormation resources.  I think it could be helpful to refine some of these permissions, especially since much of the code lives in S3 and can be difficult to audit.

The most concerning to me are the following:
* The `AdministratorAccess` policy used by the `MSAMCustomResourceRole` in `msam-browser-app-release.json`
* The `AdministratorAccess` policy used by the `DefaultSettingsResourceRole` in `msam-dynamodb-release.json`

**Comment by JimTharioAmazon** [comment]
HI there. Thank you for raising this. I agree these permissions can be narrowed down. 

I took a quick look. I think the bucket-loader custom resource for msam-browser-app-release.json could be reduced to s3 delete_object, put_object, and list_objects. The default-settings custom resource for msam-dynamodb-release.json could be reduced down to ec2 describe_regions and dynamodb put_item.

These would be quite a reduction from Admin. :-)

Let me know if you are interested in helping with this one. I am happy to work with you on a pull request to fix up these permissions. If not, I have it tentatively scheduled for a near milestone and it will be fixed either way.

**Comment by JimTharioAmazon** [comment]
DynamoDB default setting custom resource role updated to:

arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
and
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "dynamodb:PutItem",
                "ec2:DescribeRegions"
            ],
            "Resource": "*",
            "Effect": "Allow",
            "Sid": "VisualEditor0"
        }
    ]
}

**Comment by JimTharioAmazon** [comment]
Web bucket loader customer resource role is now:

arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
and
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "*",
            "Effect": "Allow",
            "Sid": "VisualEditor0"
        }
    ]
}

**Comment by tdfacer** [comment]
@JimTharioAmazon I just wanted to say thank you for looking into this.  I made some changes on my side as well.  If I see anything that can be shared I'll be sure to open a pull request.
