### ISSUE TITLE
Support discovery of on-premise equipment

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#40]
One possibility is to use AWS Systems Manager as the cloud-side integration.

Install SSM agent on each on-premise host
Tag the host to help MSAM identify it ("MSAM-Type: Encoder", "MSAM-Region: us-west-2")
MSAM's inventory process queries SSM database for inventory with above tags

Change the front-end for specific rendering needs of on-premise nodes.

**Comment by JimTharioAmazon** [comment]
Verified with a development build. This one can be closed. Thank you @morjoan.

**Comment by morjoan** [comment]
Support for discovery of on-premise equipment managed through SSM, as well as EC2s, has been added.
