### ISSUE TITLE
Add links to specific tile tabs 

### ISSUE THREAD

**Issue by morjoan** [awslabs/aws-media-services-application-mapper#46]
It would be super handy if we can link to available tile tabs directly. This would allow for sharing content and landing on a specific tile tab page that you want to highlight. Currently, you can only link to the main MSAM page which takes you to the default Tiles tab.

**Comment by JimTharioAmazon** [comment]
Correction: show a specific named diagram on startup

**Comment by JimTharioAmazon** [comment]
The URL will accept a 'diagram' parameter with the name of the diagram to show at tool start-up.

Example: https://web-app-msam-bucket/index.html?diagram=Live%20Channels
