### ISSUE TITLE
Use notification mechanisms as the default method for receiving alarm state changes

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#59]
The incoming CloudWatch alarm Lambda is installed today with the Core template. It requires an SNS topic in front of it to receive CloudWatch alarm state change notifications. That can be preconfigured with the installation.

**Comment by JimTharioAmazon** [comment]
Can we use EventBridge and subscribe to a pattern for alarm notifications. This seems to say we can: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-and-eventbridge.html

**Comment by JimTharioAmazon** [comment]
It appears we can subscribe to a CloudWatch event pattern to get notifications about alarm state changes. This seems to indicate we can use a single pattern without SNS or modifying the alarms to get the state change notification.

https://console.aws.amazon.com/events/home?region=us-east-1#/registries/aws.events/schemas/aws.cloudwatch%40CloudWatchAlarmStateChange/version/1

**Comment by JimTharioAmazon** [comment]
Need to poll the alarm state at subscription time to get the baseline, and then we can let the events notify us of state changes from there.

**Comment by morjoan** [comment]
We now have a Lambda subscribed to a CloudWatch event pattern to get notifications about alarm state changes. We manually check for the state of alarm when we first subscribe to get a baseline. We rely on the event notification to get subsequent alarm state changes.
