### ISSUE TITLE
CloudWatch Link for EMX flows

### ISSUE THREAD

**Issue by ferrenb** [awslabs/aws-media-services-application-mapper#69]
EMX flow -> Selected Item -> CloudWatch link

clicking this circles back to the MSAM application. Mirror EML channel behavior and go to cloudwork dashboard for EMX

**Comment by morjoan** [comment]
No CloudWatch logs, but can link to the main metrics page.

**Comment by JimTharioAmazon** [comment]
Using this template string:
https://${region}.console.aws.amazon.com/cloudwatch/home?region=${region}#metricsV2:graph=~();query=~'*7bAWS*2fMediaConnect*2cFlowARN*7d*20${name}

The tools is substituting the region and name of the flow to filter the list of CloudWatch Metrics in the console.
