### ISSUE TITLE
Add Alert (event) support for MediaConnect

### ISSUE THREAD

**Issue by ferrenb** [awslabs/aws-media-services-application-mapper#74]
EMX has one minute log poll time in CW currently, Alarms are VERY slow to populate - events would be best. Similar to MediaLive in MSAM today.

**Comment by morjoan** [comment]
Query from EMX team a few of weeks ago:
Q. Does mediaconnect do cloudwatch events or just metrics/logs? i can't remember...
A. We have a few Events, but they haven’t been released in the CW Events console or documentation yet. Hopefully we will get to that soon. We don’t have any CW Logs that we expose to customers.

**Comment by spainala** [comment]
JSON 
{
    "source": ["aws.mediaconnect"],
    "detail-type": ["MediaConnect Alert"]
}

**Comment by Joaquin6** [comment]
Is this JSON Schema consistent with other Media Services?

**Comment by JimTharioAmazon** [comment]
We'll hold on this one until we get some feedback from MediaConnect on the data structures they're using for their Alerts.

**Comment by morjoan** [comment]
Support added. 
Alert event looks like this: 
{
    "version": "0",
    "id": "638c00d8-ccd9-f2e7-ae10-f11cfc5515a0",
    "detail-type": "MediaConnect Alert",
    "source": "aws.mediaconnect",
    "account": "xxxx",
    "time": "2020-04-22T20:42:11Z",
    "region": "us-west-2",
    "resources": [
        "arn:aws:mediaconnect:us-west-2:xxxx:flow:1-WgQJAQMJV1MIUFhf-bc9b5327f68e:alerttestflow2"
    ],
    "detail": {
        "error-code": "ValidationException",
        "error-id": "ANiyJOI6U1O+4em1CH2O3ss3Y8Y",
        "error-message": "The decryption key for source stdsrc is invalid....).",
        "errored": False
    }
}
