### ISSUE TITLE
'Degraded' Notification State

### ISSUE THREAD

**Issue by ferrenb** [awslabs/aws-media-services-application-mapper#76]
Per customer: Not all situations are 'green,' or 'red: all hands on deck'. There are many situations where the recovery has already happened/is happening and this is a degraded state. Examples:

*Loss of single EML encode: this is covered in the pipeline redundancy. Therefore is yellow versus red for the flow.
*Loss of ground encoders: covered in redundancy, some inputs lost, but channel continues.

Customer has asked for a degraded notification state so they can review, but know the channel flow is still healthy enough for operation.

**Comment by estatt01** [comment]
I think the expectation here is that each step in the pipeline has two inputs and if both inputs are present, green status. If one input goes away (or if there is another error that doesnt impact both inputs), then yellow.  If both inputs go away or the node fails entirely, red.  For example: EMX->EML->Mux.  Each EMX has two or more sources, if one goes away, turn it yellow.  If they all go away, turn it red.  Allow the customer to say how many sources per flow (could be 1 or 2).  Likewise, EML has one or two inputs.  If one is missing, yellow. If all are missing, red.  And finally, the mux has two inputs PER member channel.  If one pipeline of a channel is missing, yellow.  If both pipelines for a member channel are missing, then red.

**Comment by JimTharioAmazon** [comment]
We need to check the accuracy of PipelinesRunningCount attribute for the DescribeChannel and DescribeMultiplex methods in boto3. This one is described as PipelinesRunningCount (integer) -- The number of currently healthy pipelines.

**Comment by dthomasson** [comment]
How would this apply to single pipeline users? Would there still be some useful degraded states to add?

**Comment by JimTharioAmazon** [comment]
If we can't use a directly API request, we'll need to use entries into the Event table to try to count the number of reported unhealthy pipelines for a given resources and infer from there.

**Comment by JimTharioAmazon** [comment]
We'll need rendering support on each node type for degraded-unselected and degraded-selected. We will need to make an evaluation in html/js/app/ui/event_alert_indicators.js and decide which render should be used. Let's try to find a way to keep the decision logic simple on the browser-side and figure out how we can supplement on the cloud-side to determine degraded.

**Comment by Joaquin6** [comment]
Do we know what the degraded state will look like? From a UI perspective?

**Comment by JimTharioAmazon** [comment]
I'm thinking we could use a pure yellow (#FFFF00) or a very washed-out red (#FFCCCC). 

![image](https://user-images.githubusercontent.com/33331284/75382234-f3605b00-588e-11ea-9dcb-9e8f017f5b36.png)

![image](https://user-images.githubusercontent.com/33331284/75382306-1428b080-588f-11ea-9e2d-a53d74bd4640.png)

**Comment by JimTharioAmazon** [comment]
We'll need to expand this to include Multiplex alerts and degraded state.

**Comment by Joaquin6** [comment]
@JimTharioAmazon PR #109 now includes Multiplex alerts and degraded state.
