### ISSUE TITLE
Provide CloudWatch event history in Monitor compartment

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#78]
We need a generic event receiver for any Media Service that emits CloudWatch events. This enhancement will capture events emitted and relate them to a cloud resource ARN. This can be displayed in an additional tabulator on the monitor tab. We should also consider adding a TTL to this table to maintain a window of past events for review.

1. Event capture in a new DDB table
2. API Gateway entry point to query based on ARN and time range (or past: min, hours, days)
3. UI support in the Monitor tab
4. CloudFormation support for installation and updates

**Comment by morjoan** [comment]
All CWE are now being captured and saved into the CloudWatchEvents DB. UI now has a tab specifically for CWE that shows up when a node has been selected.
