### ISSUE TITLE
Add documentation for MSAM REST API

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#8]
REST_API.md should include resource descriptions and invocation process.

**Comment by aredshaw** [comment]
Are you using REST APIs? If so, I might be able to help.
I would need to know the base path and endpoints.
Also, a list of possible methods and parameters.
And of course an API Key if one is required.

Have a good day,
Aaron

**Comment by Greglobrien** [comment]
Hey All, I added REST_API.MD as an initial API documentation page
