### ISSUE TITLE
MediaLive Visualization enhancement: represent pipelines separately

### ISSUE THREAD

**Issue by ferrenb** [awslabs/aws-media-services-application-mapper#80]
A customer during a demo noted it would be great to see each encoder (pipeline) visualized separately instead of a single object. Would also allow visualization of AZ flows, which would also be a handy support monitoring.

**Comment by JimTharioAmazon** [comment]
Initial notes. Connection mapping in the cloud needs to identify one or more connections between MediaLive inputs and channels, MediaLive channels and MediaPackage channels.

IDs generated for connections stored in the Content table needs to include pipeline in a way that can be calculated by the browser app. For example:

<FROM-ARN>:<TO-ARN>:<PIPELINE-#>

Currently only to-from is used for an ID.

Connection labeling needs to include pipeline.
Connection rendering should be smooth/curved for Vis.js to prevent connections from overlapping. Currently connections render straight.

**Comment by JimTharioAmazon** [comment]
Depending on the connection # we will need to specify the edge style, either CurvedCW or CurvedCCW, for clockwise or counterclockwise to achieve this kind of rendering:

![image](https://user-images.githubusercontent.com/33331284/75363343-d74cc180-586e-11ea-9d5e-953893c81e1c.png)

**Comment by Joaquin6** [comment]
@JimTharioAmazon Here is the [PR](https://github.com/awslabs/aws-media-services-application-mapper/pull/110) for this.
However, I did have a question regarding your [previous comment](https://github.com/awslabs/aws-media-services-application-mapper/issues/80#issuecomment-590140101).

Specifically on the following: `MediaLive inputs and channels, MediaLive channels and MediaPackage channels`
Meaning not to other media services _(multiplex, mediaconnect, etc...)_?  

I understood this as such and the PR only applies to those services.

CC: @morjoan
