### ISSUE TITLE
MediaLive Multiplex Alert Support

### ISSUE THREAD

**Issue by spainala** [awslabs/aws-media-services-application-mapper#82]
AWS Elemental MediaLive Multiplex introduced alerts (CloudWatch Events).  Please introduce support for these alerts.

Alert code 7001 - Communication lost from encoder
Alert code 7002 - Communication lost from multiplex
Alert code 7003 - Active Encoder Switched for Program
Alert code 7004 - Active Encoder Sent Fill or Slate Frames
Alert code 7005 - MPTS bitrate overflow

**Comment by Joaquin6** [comment]
Issue #82:

Description of changes:

Handling Multiplex Alerts
All Multiplex alerts will have a source of aws.medialive. That means the incoming alert can be from a running MediaLive Channel or a MediaLive Multiplex. There are several ways to tell them apart, but this PR simply checks the alert's detail-type value. Every multiplex alert will have Multiplex in the detail-type. In addition, multiplex alerts do not have a detail.channel_arn attribute, instead they will contain detail.multiplex_arn.

Adding alert content to multiplex nodes
Added a medialive_multiplex overlay to handle MediaLive Multiplex specific nodes. Here we handle the logic to aggregate pipeline alert count and active alarm count.

**Comment by JimTharioAmazon** [comment]
Closing and adding to 1.5.5.
