### ISSUE TITLE
Keep track of active flow with green lines

### ISSUE THREAD

**Issue by estatt01** [awslabs/aws-media-services-application-mapper#84]
MSAM can monitor systems that have redundancy features.  This request is for MSAM to keep track of which path is the active one so that a user can understand which components of their workflow are on the air. The visualization of such is a simply green line through the active components.

**Comment by Joaquin6** [comment]
Will need to use https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/mediapackage.html?highlight=mediapackage

**Comment by JimTharioAmazon** [comment]
After some thought, I'd like us to consider making this an extension of the event/alert receipt on the front-end and try to extend the concept of overlays to connection decoration/overlay as well. We have context on the pipeline # being affected by an alert, and we can judge whether to change the display of a node to degraded or failed, so I hope we can carry that forward to connection display also.

**Comment by JimTharioAmazon** [comment]
For MediaLive channel and multiplex connections, assume all inputs/outputs are normal (green) until alerts come through, and set affected connections back to black for those with active pipeline alerts.

**Comment by Joaquin6** [comment]
@JimTharioAmazon @morjoan 
https://github.com/awslabs/aws-media-services-application-mapper/pull/142
