### ISSUE TITLE
Reorganize the selected item/monitoring layout

### ISSUE THREAD

**Issue by morjoan** [awslabs/aws-media-services-application-mapper#92]
With the addition of CloudWatch events monitoring ( #78 ), the user must now keep scrolling down in the Monitoring tab in order to see all the information regarding alarms, alerts, and CW events. This doesn't seem to be the best user experience. There are a couple of ideas to improve this:

1.  Create a tab for each of these 3 items under the  Monitor section. 
OR
2. Move these 3 items (alarms, alerts, and CW events) under the Selected Item tab as they do only apply to an item/tile/node that has been selected. And perhaps remove or replace the Monitor tab with information that applies to the whole diagram and not a selected item.  See screenshot.
<img width="671" alt="Screen Shot 2020-02-13 at 8 04 52 AM" src="https://user-images.githubusercontent.com/33331296/74453694-98af1400-4e37-11ea-9cb2-4596349c1794.png"> 
OR
3. (As Jim described below) Put alarms, alerts, and CW events up the top level along with Status and Search.  These only show up when a node, tile, or edge is selected.  Selected Item and Monitoring go away basically.

**Comment by JimTharioAmazon** [comment]
I'm OK with either a single-level layout with all tabs across the top, or nested as you have above. With either approach, I'd like us to hide tabs that aren't applicable for the current context. For example, Selected Item tab hides when nothing is selected and re-appears when a node or tile is selected.

I am very curious about others' opinions about nested or flat organization of the tabs.

**Comment by morjoan** [comment]
Implemented option 3 from description above. Alerts, alarms and CW events now appear at the same level as Selected Item. Relevant tabs only show up when  a node/tile/edge is selected. Tabs are hidden when nothing is selected.
