### ISSUE TITLE
Brower Application S3 - Cloudfront Bucket Permissions Policy

### ISSUE THREAD

**Issue by Greglobrien** [awslabs/aws-media-services-application-mapper#94]
I recently installed that latest version of MSAM (1581467119) in US-West-2 after wiping out a previous install.
This new version incorporated Cloudfront which I don't think was on my previous install from November.  After letting it deploy I tried the CloudFront URL after the console said the state was 'Deployed'.  However, the page didn't load - I received an Access Denied error.  After waiting another hour and trying again, same thing.  I tried private mode and a different browser, same thing. 

curling cloudfront gives me the following: (some user specific data has been changed)
```
curl https://<random CF URL>.cloudfront.net
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>XXXXXXXXXXXXXXX</RequestId><HostId>3gFil9s66tpmcLhxnfUeHttKJMfPFa5501NemDJJmQPxKgCtEDHEXP+cNwYm9q3gkwCAi3BQpTc=</HostId></Error>
```

I checked the CloudFront permissions and it all appears to be accurate (although I don't use cloudfront much)
However I did notice the Bucket ACL no longer sets items to public (which I think is the point) even though it's referenced in the install Docs. Anyway, after setting items in the bucket to public, I was able to see the Browser App.  How can I correct this so I don't send users to the bucket directly?

**Comment by Greglobrien** [comment]
Please disregard - forgot to add the index.html to the end of my request.

**Comment by JimTharioAmazon** [comment]
Thanks Greg. We should add index.html to the default page for CloudFront. I’ll open an Issue for that.



On Feb 18, 2020, at 11:53 AM, Greglobrien <notifications@github.com> wrote:

﻿

Please disregard - forgot to add the index.html to the end of my request.
