### ISSUE TITLE
Set the default root object to index.html for the CloudFront distribution

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#95]
This will allow users to navigate to the domain only and still get to the main page. As in, https://abcdefghijk.cloudfront.net/ without index.html.

![image](https://user-images.githubusercontent.com/33331284/74777086-a3114980-524d-11ea-9048-e424782ae50d.png)

**Comment by morjoan** [comment]
Updated CloudFormation for CF with default root object set to index.html. 
Final output of main MSAM template reflects CF URL without index.html.
